### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/splash#1]
## Google Fonts Latin Core & Plus coverage

- [ ] Design all the glyphs required both in the [Latin Core](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/core_unique-glyphs.txt) + [GF Latin Plus encoding](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/plus_unique-glyphs.txt)
- [ ] Create all the comb marks as mentioned below
- [ ] Leave only the compound glyphs (e.g. `adblgrave`) marked in dark grey as pending to be created using the components

----

## Diacritics

- [x] Please ensure the definitive design is adjusted in the combining marks, so they will be ready to create the compound glyphs.
- [x] Once the definitive design is ensured in the `comb` marks Legacy marks, delete the legacy marks and add them back so they are made using the `comb` marks as components.
- [x] Diacritics need to be balanced (in weight, size, contrast) and match the style of the typeface design.
- [x] Adjust the vertical position using glyphs app locked guidelines.
- [x] Ensure related marks are consistent between them, e.g. `caron` and `circumflex`
- [x] Caron.alt need to have the alternate shape used in `Ľ` [Slovak](https://en.wikipedia.org/wiki/%C4%BD) On page 30 of [this document](http://theinsectsproject.eu/wp-content/uploads/2017/05/Insects-Project-2nd-edition_screen.pdf) you can find detailed info around the vertical Caron.
- [x] Leave a 0 sidebearings value for the marks

----
## Glyphs

- [x] The `ampersand` and `Eng` need to be consistent (in size and style) with the font. See [RUSerius](https://github.com/googlefonts/are-you-serious/issues/2#issuecomment-870693956) as reference
- [x] The German Double SS need to be fixed. This [article](https://www.lucasfonts.com/learn/1E9E) is a good reference
- [x] Currency symbols are related to the overall design and have balanced proportions
- [x] `ordfeminine` and `ordmasculine` as well as superior numbers are well proportioned and with a balanced stem thickness. [Issue of reference](https://github.com/googlefonts/cherish/issues/2#issuecomment-872268750)
- [x] `fractions` and `superior` numerals have a good proportion + weight. [Issue of reference](https://github.com/googlefonts/cherish/issues/2#issuecomment-872268750)
- [x] Check the ligatures are not wider than the original combination of letters. E.g. `fi`

----
## Spacing

- [x] Inspect the spacing and kerning of the font to ensure it is working properly and most common cases are covered. [Issue of reference](https://github.com/googlefonts/moondance/issues/1#issuecomment-940151753)
- [x] Terminal forms spacing should avoid crashes or collisions. [Issue of reference](https://github.com/googlefonts/comforter/issues/7)

**Comment by RobLeuschke** [comment]
This font is ready for review.

**Comment by vv-monsalve** [comment]
Hi @RobLeuschke, 

Please use the latest source file in DropBox `Splash.glyphs` to review and solve the following in Splash

- [x] The `cedilla` mark is the wrong way around. Please take the latest source in DropBox to adjust it.

<img width="349" alt="Screen Shot 2022-04-05 at 22 56 06" src="https://user-images.githubusercontent.com/48698976/161894267-48e56641-0185-4068-b5e8-12dd888190f8.png">
<img width="93" alt="Screen Shot 2022-04-05 at 22 56 58" src="https://user-images.githubusercontent.com/48698976/161894281-c8940bf5-5059-4f4a-9cc9-781294bb4c05.png">

- [x] Please adjust the size and position of the © ® ™ symbols as talked for [Water Brush](https://github.com/googlefonts/water-brush/issues/1#issuecomment-1079001001)

<img width="613" alt="Screen Shot 2022-04-05 at 22 55 41" src="https://user-images.githubusercontent.com/48698976/161894319-7f4ad36e-b8a6-43b0-a311-d32d14f5aa01.png">

- [x] Would you please provide an image with an example of the intended use of the current 'swash' shapes in the font?

<img width="601" alt="Screen Shot 2022-04-05 at 18 41 15" src="https://user-images.githubusercontent.com/48698976/161894353-42460ab2-c205-487f-8f8d-a751840a48d7.png">

**Comment by RobLeuschke** [comment]
I have corrected the cedilla and the © symbol. I think the ® and ™ can remain as is. I have also updated the Splash.png image to include a Swash. The SWSH glyphs are simple embellishments that can be used as underlines in display words.

**Comment by vv-monsalve** [comment]
Thanks, Rob. I'll download the latest source file from DropBox and let you know if something else is needed.

> The SWSH glyphs are simple embellishments that can be used as underlines in display words.

In that case, they should be accessed as [ornaments](https://github.com/googlefonts/allura/issues/11) instead of swash ;-)

I'll take care of that in the source file.
